ops:
  chembl_activities_asset:
    config:
      n_jobs: 8
      n_test: -1
      pchembl_min: 4
  chembl_assays_asset:
    config:
      assay_confidence_min: 8
      n_jobs: 8
      n_test: -1
  chembl_mechanisms_asset:
    config:
      n_jobs: 8
      n_test: -1
  chembl_molecules_asset:
    config:
      n_jobs: 8
      n_test: -1
  chembl_targets_asset:
    config:
      n_jobs: 8
      n_test: -1
  get_hgnc_additional_asset:
    config:
      n_jobs: 8
      n_test: -1
